## Numpy

[Numpy][]是python科学计算的核心库。它提供高性能的多维数组对象以及处理这些对象的工具

[Numpy]: http://www.numpy.org/

### Arrays对象

一个numpy array是一组相同类型的数值的阵列，这些数值由非负整数索引。
1. array.shap返回元组（行数，列数）；
2. `np.array()`初始化array，使用索引访问array元素；


In [2]:
import numpy as np

a = np.array([1, 2, 3])    # Create a rank i array
print(type(a))             # Prints "<class 'numpy.ndarray'>"
print(a.shape)             # Prints "(3, )"
print(a[0], a[1], a[2])    # Prints "1 2 3"
a[0] = 5                   # Change an element of the array
print(a)                   # Prints "[5, 2, 3]"

b = np.array([[1, 2, 3,], [4, 5, 6]])    # Create a rank 2 array
print(b.shape)                           # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])         # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy还提供了许多创建array的函数

1. **numpy.zeros()**:
```
numpy.zeros = zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.

    Parameters
    zeros(shape, dtype=float, order='C')

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.

    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
```

2. **numpy.ones()**:
```
numpy.ones = ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.

    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
```

3. **numpy.full()**:
```
numpy.full = full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.

    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
```

4. **numpy.eye()**:
```
numpy.eye = eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.

        .. versionadded:: 1.14.0

    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
```

5. **numpy.random.random()**:
```
numpy.random.random = random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)

    Return random floats in the half-open interval [0.0, 1.0).

    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::

      (b - a) * random_sample() + a

    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.

    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).

    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_sample())
    <type 'float'>
    >>> np.random.random_sample((5,))
    array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428])

    Three-by-two array of random numbers from [-5, 0):

    >>> 5 * np.random.random_sample((3, 2)) - 5
    array([[-3.99149989, -0.52338984],
           [-2.99091858, -0.79479508],
           [-1.23204345, -1.75224494]])
```

In [15]:
### import numpy as np

a = np.zeros((2, 2))
print('np.zeros((2, 2)):', a, sep='\n')

b = np.ones((1, 2))
print('np.ones((1, 2)):', b, sep='\n')

c = np.full((2, 2), 7)
print('np.full((2, 2), 7):', c, sep='\n')

d = np.eye(2)
print('np.eye(2):', d, sep='\n')

e = np.random.random((2, 2))
print('np.random.random((2, 2)):', e, sep='\n')

np.zeros((2, 2)):
[[0. 0.]
 [0. 0.]]
np.ones((1, 2)):
[[1. 1.]]
np.full((2, 2), 7):
[[7 7]
 [7 7]]
np.eye(2):
[[1. 0.]
 [0. 1.]]
np.random.random((2, 2)):
[[0.32544706 0.18270499]
 [0.50596798 0.26109955]]


### Array indexing

1. **切片Slicing**：与python中的切片索引相同，array可以是多维，所以必须指定每一维的切片；

In [26]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b.shape)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
# 所有切片操作返回的是包含请求元素的原序列的浅拷贝
print('before changing b[0, 0]:', a[0, 1])
b[0, 0] = 77
print('after changing b[0, 0]:', a[0, 1])
print('a now is', a, sep='\n')
c = a[:, :3]
print('a[:, :3]:', c, sep='\n')
print('a[:, :3].shape:', c.shape)

(2, 2)
before changing b[0, 0]: 2
after changing b[0, 0]: 77
a now is
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a[:, :3]:
[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]
a[:, :3].shape: (3, 3)


2. **切片Slicing与正负索引混合使用**：However, doing so will yield an array of lower rank than the original array(方括号个数有区别). Note that this is quite different from the way that MATLAB handles array slicing:

In [29]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:、
# (方括号个数有区别)，混合索引返回的是低维array，而不是与原array相同维array
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print('row_r1:', row_r1, 'row_r1.shape:', row_r1.shape)
print('row_r2:', row_r2, 'row_r2.shape:', row_r2.shape)

# 在列索引上也有相同效果
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print('col_r1:', col_r1, 'col_r1.shape:', col_r1.shape)
print('col_r2:', col_r2, 'col_r2.shape:', col_r2.shape)


row_r1: [5 6 7 8] row_r1.shape: (4,)
row_r2: [[5 6 7 8]] row_r2.shape: (1, 4)
col_r1: [ 2  6 10] col_r1.shape: (3,)
col_r2: [[ 2]
 [ 6]
 [10]] col_r2.shape: (3, 1)


3. **正负索引**：索引会创建新array对象，而不是引用

In [38]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2,0]]))

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

# 元素索引会创建新array对象，而不是引用
b = a[[0, 1, 2], [0, 1, 0]]
print(b)
b = [2, 3, 6]
print(a, b)

[1 4 5]
[1 4 5]
[2 2]
[2 2]
[1 4 5]
[[1 2]
 [3 4]
 [5 6]] [2, 3, 6]


正负索引的一个技巧是使用正负索引来从每一行中选取/修改元素

In [39]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(a) # prints "array([[ 1,  2,  3],
         #                [ 4,  5,  6],
         #                [ 7,  8,  9],
         #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


4. **布尔索引**：
    + 使用与原数组相同维度的布尔数组来索引，返回布尔数组中True索引的元素组成的数组；
    + 布尔索引通常用于索引满足某种条件的元素；
    + array的比较操作返回一个布尔数组，布尔数组可以用于布尔索引；

In [40]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)    # 比较操作返回一个布尔数组，a中元素大于2，则返回True；a中元素小于等于2，则返回False;


print('a > 2 return', bool_idx, sep='\n')

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

a > 2 return
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


更多关于array索引的内容，请参阅[documentation](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)


### Datatypes

numpy中array元素的数据类型可以是很多种，例如int64, float64...

In [41]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1., 2.])
print(x.dtype)

x = np.array([1, 2], dtype=np.float64)
print(x.dtype)

int64
float64
float64


### Array math

numpy为数组简单计算提供了运算符和函数：

In [44]:
import numpy as np


x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print('x + y =', x+y, sep='\n')
print('np.add(x, y) =', np.add(x, y), sep='\n')

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print('x - y =', x-y, sep='\n')
print('np.subtract(x, y) =', np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
# 不是矩阵乘法，而是元素对位相乘
print('x * y =', x*y, sep='\n')
print('np.multiply(x, y) =', np.multiply(x, y), sep='\n')

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
# 不是矩阵除法，而是元素对位相除
print('x / y =', x/y, sep='\n')
print('np.divide(x, y) =', np.divide(x, y), sep='\n')

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
# 不是矩阵开方，而是各元素开根号
print('np.sqrt(x) =', np.sqrt(x), sep='\n')

x + y =
[[ 6.  8.]
 [10. 12.]]
np.add(x, y) =
[[ 6.  8.]
 [10. 12.]]
x - y =
[[-4. -4.]
 [-4. -4.]]
np.subtract(x, y) = [[-4. -4.]
 [-4. -4.]]
x * y =
[[ 5. 12.]
 [21. 32.]]
np.multiply(x, y) =
[[ 5. 12.]
 [21. 32.]]
x / y =
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
np.divide(x, y) =
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
np.sqrt(x) =
[[1.         1.41421356]
 [1.73205081 2.        ]]


numpy使用`dot`来进行矩阵乘法，向量内积，`dot`既是模块函数，又可以是实例方法，左侧矩阵*右侧矩阵

In [45]:
import numpy as np


x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print('v.dot(w) =', v.dot(w), sep='\n')
print('np.dot(v, w) =', np.dot(v, w), sep='\n')

# Matrix / vector product; both produce the rank 1 array [29 67]
print('x.dot(v) =', x.dot(v), sep='\n')
print('v.dot(x) =', v.dot(x), sep='\n')
print('np.dot(x, v) =', np.dot(x, v), sep='\n')
print('np.dot(v, x) =', np.dot(v, x), sep='\n')

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(y.dot(x))
print(np.dot(y, x))

v.dot(w) =
219
np.dot(v, w) =
219
x.dot(v) =
[29 67]
v.dot(x) =
[39 58]
np.dot(x, v) =
[29 67]
np.dot(v, x) =
[39 58]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[23 34]
 [31 46]]


numpy使用`sum`来进行矩阵内元素求和

In [46]:
import numpy as np


x = np.array([[1, 2], [3, 4]])


print(np.sum(x))             # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))     # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))     # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


更多关于数组运算的方法，请参阅[documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html)

`array.T`返回array的转置

In [47]:
import numpy as np


x = np.array([[1, 2], [3, 4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1, 2, 3])
print(v)    # Prints "[1, 2, 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


关于所有数组的方法，请参阅[docmentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)

### Broadcasting

Broadcasting是允许numpy对不同shape的数组进行算术运算的一个重要机制。大多数情况下，我们拿到的是一个smaller array和一个larger array，并且我们希望多次使用smaller array来对larger array进行多次操作。

例如，假设我们想要对数组x的每一行加上一个常向量v，我们可以用一下方法实现：

In [48]:
import numpy as np


# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**numpy.empty_like()**:
```
numpy.empty_like = empty_like(...)
    empty_like(prototype, dtype=None, order='K', subok=True)

    Return a new array with the same shape and type as a given array.

    Parameters
    ----------
    prototype : array_like
        The shape and data-type of `prototype` define these same attributes
        of the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.

        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if ``prototype`` is Fortran
        contiguous, 'C' otherwise. 'K' means match the layout of ``prototype``
        as closely as possible.

        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.

    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data with the same
        shape and type as `prototype`.

    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    zeros_like : Return an array of zeros with shape and type of input.
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
```

上述方法可以实现；但是当矩阵x非常大时，在python中执行循环会十分耗费时间；注意到矩阵x的每一行都加上向量v等价于垂直地堆叠行向量v来构造矩阵vv，并用矩阵vv与矩阵x相加。实现如下：

In [49]:
import numpy as np


# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


但是上述方法耗费内存，空间复杂度换取时间复杂度；

下面我们介绍numpy的broadcasting机制。numpy的broadcasting机制允许我们实现上述操作而不用创建多个v向量的副本，使用broadcasting实现如下：

In [50]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

**Broadcasting基本准则**：
1. 对两个阵进行操作时，NumPy逐元素地比较他们的形状，从后面的维度向前执行。If the arrays do not have the same rank, **prepend**(意味着从后往前) the shape of the lower rank array with 1s until both shapes have the same length.
2. 当以下情形出现时，两个维度是compatible：a)它们相等; b)其中一个是1;The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. 如果两个矩阵在各个维度上competible，则他们是可broadcasting的；The arrays can be broadcast together if they are compatible in all dimensions.
4. broadcasting后，结果矩阵的尺寸与各个输入矩阵的各维度最大尺寸相同。After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. 尺寸为1的维度将延展或“复制”到与另一个维度匹配。In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

详细解释请参阅[官方文档](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)和[参考材料](https://blog.csdn.net/hongxingabc/article/details/53149655)

In [52]:
import numpy as np

# Compute outer product of vertors
v = np.array([1, 2, 3])  # v has shape (3, )
w = np.array([4, 5])     # w has shape (2, )
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


**Numpy Documentation**

关于numpy的详细信息，请查看[官方文档](http://docs.scipy.org/doc/numpy/reference/)

### SciPy

Numpy提供了高性能的多维数组以及计算、操作这些数组的基本工具。[SciPy](http://docs.scipy.org/doc/scipy/reference/)构建在numpy的基础上，提供了大量操作numpy数组的函数，这有利于不同类型的科学和工程应用。

熟悉SciPy的最佳路径是学习[SciPy Documentation](http://docs.scipy.org/doc/scipy/reference/index.html)。在此处，我们只提及对于本课程有用的部分SciPy内容。

**Image operations**

SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

In [53]:
from scipy.misc import imread, imsave, imresize

img = imread('./img/IMG_1889.JPG')
print(img.dtype, img.shape)

img_tinted = img * [1, 0.95, 0.9]


ImportError: cannot import name 'imread'